%YAML:1.0
---
#aruco-dictionary: ARUCO_MIP_16h3 #dictionnary used
aruco-detectMode: DM_FAST #DM_NORMAL 
aruco-cornerRefinementM: CORNER_LINES 
aruco-thresMethod: THRES_ADAPTIVE
aruco-maxThreads: -1
aruco-borderDistThres: 0
aruco-lowResMarkerSize: 10
aruco-minSize: 0.
aruco-minSize_pix: -1
aruco-enclosedMarker: 0
aruco-NAttemptsAutoThresFix: 3
aruco-AdaptiveThresWindowSize: -1
aruco-ThresHold: 25
aruco-AdaptiveThresWindowSize_range: 0
aruco-markerWarpPixSize: 5
aruco-autoSize: 0
aruco-ts: 2.5000000000000000e-01
aruco-pyrfactor: 2.
aruco-error_correction_rate: 1
aruco-trackingMinDetections: 0
aruco-closingSize: 0
